source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/mafeng-Bryant/Specs.git'
use_frameworks!
target 'MDevice_Example' do
  pod 'MDevice', :path => '../'

  target 'MDevice_Tests' do
    inherit! :search_paths

    
  end
end
